# Generated by Django 5.0.1 on 2024-01-23 18:15

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name_plural': 'Category Blog',
            },
        ),
        migrations.CreateModel(
            name='LabelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Label Name')),
            ],
            options={
                'verbose_name_plural': 'Label Category',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('createAt', models.DateTimeField(auto_now=True, verbose_name='Create At')),
                ('image', models.ImageField(blank=True, upload_to='Blog', verbose_name='Image')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, populate_from='title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoryblog', verbose_name='Category')),
                ('label', models.ManyToManyField(to='blog.labelcategory', verbose_name="Label's")),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
