# Generated by Django 5.0.1 on 2024-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim bilgileri',
            },
        ),
    ]
