# Generated by Django 5.0.1 on 2024-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Biografi Tarih')),
                ('content', models.TextField(verbose_name='Biografi içerik')),
            ],
            options={
                'verbose_name': 'Biografi',
                'verbose_name_plural': 'Biyografiler',
            },
        ),
    ]
