# Generated by Django 5.0.1 on 2024-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Anasayfa Arkaplan')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('title', models.CharField(max_length=50, verbose_name='Anasayfa Başlık')),
                ('subtitle', models.TextField(verbose_name='Anasayfa Altbaşlık')),
            ],
            options={
                'verbose_name': 'Anasayfa Arkaplan',
                'verbose_name_plural': 'Anasayfa Arkaplan',
            },
        ),
    ]
